[package]
name = "london_tube"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.228", features = ["derive"]}
reqwest = { version = "0.12.24", features = ["json","blocking"],default=false }
serde_json = "1.0.145"
graph_lib={workspace=true}
